name: Compile cmdstanpy on windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          environment-file: env.yml
          init-shell: >-
           bash
          cache-environment: true
          post-cleanup: 'all'
      - name: Run pyinstaller
        run: pyinstaller -F --add-data bernoulli.stan:. --add-data bernoulli.data.json:. --add-binary $CMDSTAN:./cmdstan  --runtime-hook env_patch.py cmd.py
        shell: bash -el {0}
      - uses: actions/upload-artifact@v3
        with:
          name: cmd
          path: dist/cmd.exe

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: cmd
    - name: Run cmd.exe
      run: ./cmd.exe
