name: Compile cmdstanpy on windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: '1.5.6-0'
          environment-file: env.yml
          init-shell: >-
           bash
          cache-environment: true
          post-cleanup: 'all'
      - name: ls root
        run: ls "/"
        shell: bash -el {0}
      - name: ls program x86
        run: ls "/Program Files (x86)"
        shell: bash -el {0}
      - name: ls program oneAPI
        run: ls "/Program Files (x86)/Intel/oneAPI/mkl"
        shell: bash -el {0}
      - name: Run pyinstaller
        run: pyinstaller cmd.spec
        shell: bash -el {0}
      - uses: actions/upload-artifact@v3
        with:
          name: cmd
          path: dist/cmd.exe

  test:
    runs-on: windows-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: cmd
    - run: ./cmd.exe
